#!/bin/bash
# GitHub Actions Secrets Setup Helper
#
# This script helps you understand what secrets need to be configured
# in your GitHub repository for CI/CD to work properly

echo "🔐 VibeChat GitHub Actions Secrets Configuration"
echo "=============================================="
echo ""
echo "The following secrets need to be configured in your GitHub repository:"
echo "Go to: Settings > Secrets and variables > Actions"
echo ""
echo "1. EC2_HOST"
echo "   - Your EC2 instance public IP or domain name"
echo "   - Example: 54.123.456.789"
echo ""
echo "2. EC2_USER"
echo "   - SSH user for your EC2 instance (usually 'ubuntu' for Ubuntu AMI)"
echo "   - Example: ubuntu"
echo ""
echo "3. EC2_PRIVATE_KEY"
echo "   - The private SSH key for your EC2 instance (.pem file content)"
echo "   - To get this:"
echo "     a. Open your EC2 key pair (.pem file) with a text editor"
echo "     b. Copy the entire contents"
echo "     c. Paste as the secret value"
echo "     d. Keep your private key secure - never commit it to git"
echo ""
echo "Setup Instructions:"
echo "=================="
echo ""
echo "1. Generate or use existing EC2 key pair:"
echo "   - If you don't have one, create it in AWS EC2 > Key pairs"
echo "   - Download the .pem file and keep it safe"
echo ""
echo "2. Get your EC2 instance details:"
echo "   - Public IPv4 address: Found in EC2 Dashboard"
echo "   - User: Depends on AMI (ubuntu, ec2-user, admin, etc.)"
echo ""
echo "3. Add secrets to GitHub:"
echo "   - Open your GitHub repository"
echo "   - Go to Settings > Secrets and variables > Actions"
echo "   - Click 'New repository secret' for each:"
echo ""
echo "   Secret 1: EC2_HOST"
echo "   Value: Your EC2 public IP (e.g., 54.123.456.789)"
echo ""
echo "   Secret 2: EC2_USER"
echo "   Value: ubuntu (or your AMI's default user)"
echo ""
echo "   Secret 3: EC2_PRIVATE_KEY"
echo "   Value: Contents of your .pem file"
echo ""
echo "4. Verify SSH connection works (from your local machine):"
echo "   ssh -i /path/to/your/key.pem ubuntu@your-ec2-ip"
echo ""
echo "5. Once secrets are added, the GitHub Actions workflow will:"
echo "   - Run tests on every push and pull request"
echo "   - Deploy to EC2 on every push to main branch"
echo ""
echo "Testing the Deployment:"
echo "====================="
echo ""
echo "1. Push a commit to the main branch:"
echo "   git push origin main"
echo ""
echo "2. Go to GitHub Actions tab to see the workflow running"
echo ""
echo "3. Once complete, check your EC2 instance:"
echo "   - SSH into your EC2 instance"
echo "   - Check service status: sudo systemctl status vibechat-backend"
echo "   - View logs: tail -f /home/ubuntu/vibechat/logs/backend.log"
echo ""
echo "Troubleshooting:"
echo "==============="
echo ""
echo "- Permission denied (publickey): Check that EC2_PRIVATE_KEY secret is correct"
echo "- Connection refused: Check EC2 security groups allow SSH (port 22) and HTTP (ports 80, 3006, 5006)"
echo "- Service won't start: Check .env files are configured and logs for errors"
echo ""
